# Generated by Django 4.2.16 on 2025-03-23 15:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('subjectName', models.CharField(max_length=100)),
                ('classType', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('qr_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTb',
            fields=[
                ('courseID', models.IntegerField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=255)),
                ('total_classes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserTb',
            fields=[
                ('userID', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=255)),
                ('lName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255)),
                ('phoneNum', models.CharField(max_length=255)),
                ('macAddress', models.CharField(max_length=255)),
                ('userType', models.CharField(choices=[('Staff', 'Staff'), ('Student', 'Student')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentTb',
            fields=[
                ('enrollmentID', models.AutoField(primary_key=True, serialize=False)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceRecordingQR.coursetb')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceRecordingQR.usertb')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecordingTb',
            fields=[
                ('attdID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('classType', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceRecordingQR.coursetb')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceRecordingQR.usertb')),
            ],
        ),
    ]
